language: php
services:
- docker

before_install:
- docker pull woodyxiong/php7.2-swoole:latest
- pwd
- docker run -it -v $(pwd):/data/www woodyxiong/php7.2-swoole:latest composer install

script:
- docker run -it -v $(pwd):/data/www woodyxiong/php7.2-swoole:latest vendor/bin/phpunit -c Test/phpunit.xml --coverage-text
